config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  get '/terms', to: 'home#terms'
  get '/contact', to: 'home#contact'
  get '/auth/twitter/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/search', to: 'books#search'
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :url, presence: true
  validates :image_url, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :books, dependent: :destroy
  validates :name, presence: true
  validates :nickname, presence: true
  validates :image_url, presence: true
  
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    nickname = auth[:info][:nickname]
    name = auth[:info][:name]
    image_url = auth[:info][:image]
    self.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = name
      user.nickname = nickname  
      user.image_url = image_url
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  include BooksHelper

  def logged_in_user
    redirect_to root_path unless logged_in?
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :logged_in_user, only:[:search]

  def search
    if params[:keyword].present?
      retry_count = 0
      begin
        books = Amazon::Ecs.item_search(
          params[:keyword],
          search_index:  'Books',
          dataType: 'script',
          response_group: 'ItemAttributes, Images',
          country:  'jp',
          power: "Not kindle"
        )
      rescue => e
        retry_count += 1
        logger.error e.message
        if retry_count < 5
          sleep(2)
          retry
        end
    end
        @books = []
        books.items.each do |item|
          book = current_user.books.build(
            title: item.get('ItemAttributes/Title'),
            image_url: item.get('LargeImage/URL'),
            url: item.get('DetailPageURL'),
          )
          @books << book
        end
      end
    end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      flash[:info] = "本を登録しました"
      redirect_to user_path(@current_user)
    else 
      flash[:info] = "登録に失敗しました"
      redirect_to request.referrer || root_url
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:info] = "登録した本を削除しました"
    redirect_to request.referrer || root_url
  end
  
  private

    def book_params
      params.require(:book).permit(:title,:image_url,:url)
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
  def contact
  end

  def terms
  end
  
  def home
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    retry_count = 0
    begin
      user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    rescue => e
      retry_count += 1
      logger.error e.message
      if retry_count < 5
        sleep(3)
        retry
      else
        flash[:info] = "Twitter認証できませんでした 管理者にお問い合わせください"
        redirect_to root_path
      end
    end 
    if log_in user
      flash[:info] = "Twitter認証しました"
      redirect_to user
    else
      redirect_to root_path
    end
  end

  def destroy
    log_out
    flash[:info] = "ログアウトしました"
    redirect_to root_path 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only:[:destroy]
  before_action :correct_user, only:[:destroy]

  def show
    @user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page], per_page: 10)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 9)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:info] = "全ての登録情報を削除し、退会完了いたしました"
    redirect_to root_url
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless @user == @current_user
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "rebook"
    if page_title.empty?
      base_title
    else
      page_title
    end
  end
  
end

app/helpers/books_helper.rb
module BooksHelper

  def currentuser_book_correct?
    @books.user_id == session[:user_id]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    if(user_id = session[:user_id])
      @current_user ||= User.find_by(id:session[:user_id])
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def currentuser_correct?
    @user.id == session[:user_id]
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/new.html.erb
<本登録・検索画面>

app/views/books/search.html.erb
<div class="book_lst">
  <% if @books.present? %>
    <% @books.each do |book| %>
      <div class="book_bx">
        <%= link_to image_tag(book.image_url), book.url %>
        <div class="book_ttl">
          <%= book.title %>
        </div>
        <div class="book_btn">
          <%= form_with model: @books, url: books_path do |f| %>
            <%= f.hidden_field :title, value: book.title %>
            <%= f.hidden_field :url, value: book.url %>
            <%= f.hidden_field :image_url, value: book.image_url %>
            <%= f.submit '登録', data: { confirm: "この本(#{book.title})を登録しますか？" }, class: "btn btn-info" %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/home/agreement.html.erb
<% provide(:title, '利用規約') %>
<h2 class="page_title">利用規約</h2>
<div class="contents_item">
  <ul>
    <li>この利用規約（以下，「本規約」といいます。）は、リブックがこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</li>
  </ul>
</div>
<h3 class="contents_title">第1条（適用）</h3>
<div class="contents_item">
  <ul>
    <li>本規約は，ユーザーと当サイトとの間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
  </ul>
</div>
<h3 class="contents_title">第2条（利用登録）</h3>
<div class="contents_item_number">
  <ul>
    <li>登録希望者が当サイトの定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。</li>
    <li>当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
      <ul>
        <li>（1）利用登録の申請に際して虚偽の事項を届け出た場合</li>
        <li>（2）本規約に違反したことがある者からの申請である場合</li>
        <li>（3）未成年者，成年被後見人，被保佐人または被補助人のいずれかであり，法定代理人，後見人，保佐人または補助人の同意等を得ていなかった場合</li>
        <li>（4）反社会的勢力等（暴力団，暴力団員，右翼団体，反社会的勢力，その他これに準ずる者を意味します。）である，または資金提供その他を通じて反社会的勢力等の維持，運営もしくは経営に協力もしくは関与する等反社会的勢力との何らかの交流もしくは関与を行っていると当社が判断した場合</li>
        <li>（5）その他，当サイトが利用登録を相当でないと判断した場合</li>
      </ul>
    </li>
  </ul>
</div>
<h3 class="contents_title">第3条（ユーザーIDおよびパスワードの管理）</h3>
<div class="contents_item_number">
  <ul>
    <li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを管理するものとします。</li>
    <li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
  </ul>
</div>
<h3 class="contents_title">第4条（利用料金および支払方法）</h3>
<div class="contents_item_number">
  <ul>
    <li>ユーザーは，本サービス利用の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。</li>
    <li>ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</li>
  </ul>
</div>
<h3 class="contents_title">第5条（禁止事項）</h3>
<div class="contents_item">
  <ul>
    <li>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。
      <ul>
        <li>（1）法令または公序良俗に違反する行為</li>
        <li>（2）犯罪行為に関連する行為</li>
        <li>（3）当社のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
        <li>（4）当社のサービスの運営を妨害するおそれのある行為</li>
        <li>（5）他のユーザーに関する個人情報等を収集または蓄積する行為</li>
        <li>（6）他のユーザーに成りすます行為</li>
        <li>（7）当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
        <li>（8）当社，本サービスの他の利用者または第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
        <li>（9）過度に暴力的な表現，露骨な性的表現，人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現，自殺，自傷行為，薬物乱用を誘引または助長する表現，その他反社会的な内容を含み他人に不快感を与える表現を，投稿または送信する行為</li>
        <li>（10）営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。），性行為やわいせつな行為を目的とする行為，面識のない異性との出会いや交際を目的とする行為，他のお客様に対する嫌がらせや誹謗中傷を目的とする行為，その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
        <li>（11）宗教活動または宗教団体への勧誘行為</li>
        <li>（12）その他，当社が不適切と判断する行為</li>
      </ul>
    </li>
  </ul>
</div>
<h3 class="contents_title">第6条（本サービスの提供の停止等）</h3>
<div class="contents_item_number">
  <ul>
    <li>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
      <ul>
        <li>（1）本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>（2）地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
        <li>（3）コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>（4）その他，当社が本サービスの提供が困難と判断した場合</li>
      </ul>
    </li>
    <li>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害について，理由を問わず一切の責任を負わないものとします。</li>
  </ul>
</div>
<h3 class="contents_title">第7条（著作権）</h3>
<div class="contents_item_number">
  <ul>
    <li>ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報のみ，本サービスを利用し，投稿または編集することができるものとします。</li>
    <li>ユーザーが本サービスを利用して投稿または編集した文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当社は，本サービスを利用して投稿または編集された文章，画像，映像等を利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。</li>
    <li>前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他知的財産権はすべて当社または当社にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</li>
  </ul>
</div>
<h3 class="contents_title">第8条（利用制限および登録抹消）</h3>
<div class="contents_item_number">
  <ul>
    <li>当社は，以下の場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。
      <ul>
        <li>（1）本規約のいずれかの条項に違反した場合</li>
        <li>（2）登録事項に虚偽の事実があることが判明した場合</li>
        <li>（3）破産，民事再生，会社更生または特別清算の手続開始決定等の申立がなされたとき</li>
        <li>（4）1年間以上本サービスの利用がない場合</li>
        <li>（5）当社からの問い合わせその他の回答を求める連絡に対して30日間以上応答がない場合</li>
        <li>（6）第2条第2項各号に該当する場合</li>
        <li>（7）その他，当社が本サービスの利用を適当でないと判断した場合</li>
      </ul>
    </li>
    <li>前項各号のいずれかに該当した場合，ユーザーは，当然に当社に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。</li>
    <li>当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
  </ul>
</div>
<h3 class="contents_title">第9条（保証の否認および免責事項）</h3>
<div class="contents_item_number">
  <ul>
    <li>当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
    <li>当社は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
    <li>前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
    <li>当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
  </ul>
</div>
<h3 class="contents_title">第10条（サービス内容の変更等）</h3>
<div class="contents_item">
  <ul>
    <li>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</li>
  </ul>
</div>
<h3 class="contents_title">第11条（利用規約の変更）</h3>
<div class="contents_item">
  <ul>
    <li>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。</li>
  </ul>
</div>
<h3 class="contents_title">第12条（通知または連絡）</h3>
<div class="contents_item">
  <ul>
    <li>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。</li>
  </ul>
</div>
<h3 class="contents_title">第13条（権利義務の譲渡の禁止）</h3>
<div class="contents_item">
  <ul>
    <li>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</li>
  </ul>
</div>
<h3 class="contents_title">第14条（準拠法・裁判管轄）</h3>
<div class="contents_item_number">
  <ul>
    <li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
    <li>本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
  </ul>
</div>

app/views/home/contact.html.erb
<% provide(:title, 'お問い合わせ') %>
<div class="contents_item">
  <h3>お問い合わせ</h3>
  <ul>
    <li>当サイトに関するお問い合わせやご要望がございましたらこちらの連絡先まで送って頂きますようお願いいたします。
    <ul>
      <li>・Email: hrswkhd@gmail.com</li>
      <li><a href="https://twitter.com/mwkpgdjp">・製作者Twitterアカウント</a></li>
    </ul>
    <% if logged_in? %>
      <li>退会をご希望の方は<span><%= link_to "こちら", user_path(@current_user.id), method: :delete, data: { confirm: "退会しますか？" } %></span>からお願いします。</li>
    <% end %>
  </ul>
</div>

app/views/home/home.html.erb
<div class="home">
  <%= image_tag('/352c50b0ab55e1dbf223b376ab62f439_m.jpg') %>
  <div class="home_item">
    <p><%= link_to 'Twitterでログインしてはじめる', '/auth/twitter', :class => "btn btn-info"%></p>
    <p>rebookは本登録型SNSサイトです</p>
    <p>あなたが読んだ本を検索して登録してみましょう</p>
  </div>
</div>

app/views/home/login.html.erb
<p>memboはあなたの代わりに読んだ本を記憶するWebサービスです。<p>
<p><%= link_to 'Twitterでログインしてはじめる', '/auth/twitter' %></p>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-dark">
    <div class="mx-auto">
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <%= link_to 'このサイトについて', root_path %>
        </li>
        <li class="nav-item">
          <%= link_to '利用規約', terms_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'お問い合わせ', contact_path %>
        </li>
      </ul>
      <p>© rebook</p>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <div class="container">
      <%= link_to "rebook", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <% if logged_in? %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "MYPAGE", user_path(@current_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "USERS", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "LOGOUT", logout_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
            <%= form_with(url: search_path, method: :get, class: "form-inline my-2 my-lg-0", local: true) do |f| %>
              <%= f.text_field :keyword, placeholder: "本のタイトルを入力", class: "form-control" %>
              <%= button_tag type: "submit", class: "btn btn-outline-dark my-2 my-sm-0" do %><i class="fa fa-search"></i><% end %>  
            <% end %>
        <% else %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'LOGIN', '/auth/twitter', class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "USERS", users_path, class: "nav-link" %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="row">
          <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_list.html.erb
<% @books.each do |book| %>
  <div class="book_bx">
    <%= link_to image_tag(book.image_url), book.url %>
    <div class="book_ttl">
      <%= book.title %>
    </div>
    <!--<div class="book_btn">
      <% if currentuser_correct? %>
        <%= link_to  "削除", book, method: :delete, :class => "btn btn-info", data: { confirm: "この本を削除しますか？" } %>
      <% end %>
    </div>-->    
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<div class="user_lst">
  <% @users.each do |user| %>
    <div class="user_pnl">
      <%= image_tag user.image_url %>
      <%= link_to user.name, user %>
      <%= content_tag :span, user.books.count, class: "fa fa-book" %>
      <div class="twitter_link">
        <%= link_to "https://twitter.com/#{user.nickname}" do %>
          <i class="fa fa-twitter"></i> 
        <% end %>
      </div>
    </div>
  <% end %>
  <%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}さんのページ") %>
<div class="usershw_pnl">
  <%= image_tag  @user.image_url %>
  <%= @user.name %>
  <!--<% if currentuser_correct? %>
     <%= link_to "本を登録する", search_path, :class => "btn btn-info"%>
  <% end %>-->
  <%= content_tag :span, @user.books.count, class: "fa fa-book" %>
  <%= link_to "https://twitter.com/#{@user.nickname}" do%>
    <i class="fa fa-twitter" ></i>
  <% end %>
</div>
<div class='book_lst'>
  <%= render 'users/list' %>
</div>